esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

espnow:
  id: espnow_component
  on_boot:
    priority: -100
    then:
      - wait_until:
          wifi.connected:
      - while:
          condition:
            wifi.connected:
          then:
            - espnow.send:
                id: espnow_send_bcast
                data: '{"msg_type":"DATA", "voc_index":150, "nox_index":75}'
            - logger.log: "Sent dummy DATA packet"
            - delay: 10s
