esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

esphome:
  on_boot:
    priority: -100
    then:
      - wait_until:
          wifi.connected:
      - while:
          condition:
            wifi.connected:
          then:
            - espnow.broadcast:
                data: '{"msg_type":"DATA", "voc_index":150, "nox_index":75}'
            - logger.log: "Sent dummy DATA packet"
            - delay: 10s

espnow:
  # The component is enabled here, but the logic that uses it
  # is in the on_boot trigger above.